ARG base_image="ubuntu:20.04"
FROM ${base_image}
ENV DEBIAN_FRONTEND noninteractive

ARG build_type="Release"

WORKDIR /workspace

# pre-requisites
RUN apt update && apt install -y git wget python-is-python3 software-properties-common lsb-release ca-certificates build-essential python3-dev python3-numpy python3-setuptools python3-wheel python3-pip
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
RUN apt update && apt install -y cmake time

# build ONNX runtime wheel package
RUN git clone --recursive https://github.com/microsoft/onnxruntime
RUN cd onnxruntime && ./build.sh --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=`cat ./VERSION_NUMBER` --config $build_type --skip_tests --build_wheel
RUN pip3 install /workspace/onnxruntime/build/Linux/$build_type/dist/*.whl
RUN pip3 install psutil onnx coloredlogs torch packaging transformers sympy
RUN pip3 install -U numpy
