ARG base_image="rocm/dev-ubuntu-22.04:5.2.3-complete"
FROM ${base_image}
ENV DEBIAN_FRONTEND noninteractive
ENV ROC_USE_FGS_KERNARG=0
ARG branch="develop"
ARG rocm_release="5.2.3"

WORKDIR /workspace

# fix up repository to avoid "debian" so it continues to work after default debian is updated
RUN sed -e s/debian/${rocm_release}/g /etc/apt/sources.list.d/rocm.list > /etc/apt/sources.list.d/rocm${rocm_release}.list
RUN rm /etc/apt/sources.list.d/rocm.list

# prerequisites
RUN apt update && apt install -y git libopencv-dev cmake

# build MIGraphX
RUN apt install -y half
RUN pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz
RUN mkdir /src
RUN cd /src && git clone --branch ${branch} https://github.com/ROCmSoftwarePlatform/AMDMIGraphX
RUN cd /src/AMDMIGraphX && rbuild package --cxx /opt/rocm/llvm/bin/clang++ -d /src/AMDMIGraphX/deps -B /src/AMDMIGraphX/build -DPYTHON_EXECUTABLE=/usr/bin/python3
RUN cd /src/AMDMIGraphX/build && dpkg -i *.deb

# build migx tool
COPY half.hpp /usr/local/include/half.hpp
RUN cd /src && git clone https://github.com/mvermeulen/rocm-migraphx
RUN cd /src/rocm-migraphx/tools/migx && ./build_migx.sh
