FROM ubuntu:18.04

ARG PREFIX=/usr/local

# Support multiarch
RUN dpkg --add-architecture i386

# Add rocm repository
RUN sh -c 'echo deb [arch=amd64 trusted=yes] http://compute-artifactory.amd.com/artifactory/list/rocm-osdb-deb compute-rocm-dkms-no-npi-hipclang 2363 > /etc/apt/sources.list.d/rocm.list'
# Install dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated \
    apt-utils \
    build-essential \
    cmake \
    curl \
    doxygen \
    gdb \
    git \
    lcov \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    software-properties-common \
    wget \
    rocm-device-libs \
    miopen-hip \
    rocblas \
    zlib1g-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
 
# Workaround broken rocm packages
RUN ln -s /opt/rocm-* /opt/rocm
RUN sed -i 's/hip_STATIC_DEPENDS/hip/g' /opt/rocm/miopen/lib/cmake/miopen/miopen-config.cmake
RUN sed -i '/Boost/d' /opt/rocm/miopen/lib/cmake/miopen/miopen-config.cmake
RUN sed -i '/rocblas/d' /opt/rocm/miopen/lib/cmake/miopen/miopen-config.cmake

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Add MIGraphX and rocm-migraphx
RUN mkdir /src
RUN cd /src && git clone https://github.com/ROCmSoftwarePlatform/AMDMIGraphX
RUN cd /src/AMDMIGraphX && git checkout master
RUN cd /src && git clone https://github.com/mvermeulen/rocm-migraphx

# Install rbuild
RUN pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz

# Install dependencies
#ADD dev-requirements.txt /dev-requirements.txt
#ADD requirements.txt /requirements.txt
RUN rbuild prepare --cxx /opt/rocm/llvm/bin/clang++ -d $PREFIX -S /src/AMDMIGraphX

# Install rocm-cmake
RUN cget -p $PREFIX install -U RadeonOpenCompute/rocm-cmake@master

# Mark build as hip-clang
RUN touch /root/hip-clang
