# build MIGraphX *.deb packages from source
#
ARG base_image="rocm/dev-ubuntu-20.04:5.0-complete"
FROM ${base_image}

ARG branch="develop"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y git cmake

# install rbuild
RUN pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz

# build MIGraphX from source
RUN mkdir -p /migraphx
RUN cd /migraphx && git clone --depth=1 --branch ${branch} https://github.com/ROCmSoftwarePlatform/AMDMIGraphX src
RUN cd /migraphx && rbuild package --cxx /opt/rocm/llvm/bin/clang++ -d /migraphx/deps -B /migraphx/build -S /migraphx/src -DPYTHON_EXECUTABLE=/usr/bin/python3
