ARG base_image="rocm/dev-ubuntu-20.04:5.0-complete"
FROM ${base_image}
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /workspace

# pre-requisites
RUN apt update && apt install -y git wget software-properties-common lsb-release python3-dev python3-numpy python3-setuptools python3-wheel python3-pip
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
RUN apt update && apt install -y cmake

# build ONNX runtime wheel package
RUN git clone --recursive https://github.com/microsoft/onnxruntime
RUN cd onnxruntime && ./build.sh --build_shared_lib --parallel --build_wheel
