FROM ROCM_BASE
RUN sed -e s/debian/ROCM_RELEASE/g /etc/apt/sources.list.d/rocm.list > /etc/apt/sources.list.d/rocmROCM_RELEASE.list
RUN rm /etc/apt/sources.list.d/rocm.list
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y git cmake python-pip python3-pip zlib1g-dev unzip autogen autoconf libtool wget
RUN apt update && apt install -y libnuma-dev rocm-cmake rocm-libs miopen-hip
RUN apt update && apt install -y libopencv-dev kmod
RUN mkdir /src
RUN cd /src && git clone https://github.com/ROCmSoftwarePlatform/AMDMIGraphX
RUN cd /src && git clone https://github.com/mvermeulen/rocm-migraphx
RUN cd /src/rocm-migraphx/scripts && ./build_prereqs.sh
COPY half.hpp /usr/local/include/half.hpp
ENV LD_LIBRARY_PATH=/usr/local/lib:
RUN cd /src/rocm-migraphx/scripts && ./build_migraphx.sh
