ARG DOCKERBASE=rocm-migraphx:3.5
FROM $DOCKERBASE
RUN cd /src/AMDMIGraphX && git pull
ENV DEBIAN_FRONTEND=noninteractive
ENV HIP_DOCKER_WORKAROUND=1
# Add opencv
RUN apt update && apt install -y libopencv-dev
RUN cd /src/AMDMIGraphX && /src/rocm-migraphx/scripts/build_migraphx.sh
# Add pre-tuned db
COPY miopen /root/.config/miopen/
# Build the migx driver
RUN cd /src/rocm-migraphx/tools/migx && ./build_migx.sh