ARG ROCM_RELEASE=3.1
ARG ROCM_BASE=rocm/dev-ubuntu-18.04:${ROCM_RELEASE}
FROM ${ROCM_BASE}
RUN sed -e s/debian/${ROCM_BASE}/g /etc/apt/sources.list.d/rocm.list > /etc/apt/sources.list.d/rocm${ROCM_RELEASE}.list
RUN rm /etc/apt/sources.list.d/rocm.list
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y git cmake python-pip python3-pip zlib1g-dev unzip autogen autoconf libtool wget
RUN apt update && apt install -y libnuma-dev rocm-cmake rocm-libs miopen-hip
RUN mkdir /src
RUN cd /src && git clone https://github.com/ROCmSoftwarePlatform/AMDMIGraphX
RUN cd /src && git clone https://github.com/mvermeulen/rocm-migraphx
