ARG base_image="rocm/pytorch:rocm4.5.2_ubuntu18.04_py3.8_pytorch_1.10.0"
FROM ${base_image}
ENV DEBIAN_FRONTEND noninteractive

ARG branch="branch_for_ort"

WORKDIR /workspace

# pre-requisites
RUN apt update && apt install -y git wget software-properties-common lsb-release python3-dev python3-numpy python3-setuptools python3-wheel python3-pip
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
RUN apt update && apt install -y cmake

# build MIGraphX
RUN apt install -y half
RUN pip3 install https://github.com/RadeonOpenCompute/rbuild/archive/master.tar.gz
RUN mkdir migraphx
RUN cd migraphx && git clone --depth=1 --branch ${branch} https://github.com/ROCmSoftwarePlatform/AMDMIGraphX src
RUN cd migraphx && rbuild package --cxx /opt/rocm/llvm/bin/clang++ -d deps -B build -S /workspace/migraphx/src -DPYTHON_EXECUTABLE=/usr/bin/python3
RUN cd migraphx/build && dpkg -i *.deb

# build ONNX runtime wheel package
COPY patch.enable_gfx1030 /workspace
RUN git clone --recursive https://github.com/microsoft/onnxruntime
RUN patch onnxruntime/cmake/onnxruntime_providers.cmake < patch.enable_gfx1030
RUN cd onnxruntime && ./build.sh --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=`cat ./VERSION_NUMBER` --config Release --skip_tests --build_wheel --use_migraphx --use_rocm --rocm_version=4.5.2 --rocm_home /opt/rocm
RUN pip3 install /workspace/onnxruntime/build/Linux/Release/dist/*.whl

# install pre-reqs for running benchmarks
RUN pip3 install psutil onnx coloredlogs packaging transformers sympy
RUN pip3 install -U numpy
